fix: regex now closer matches the commitlint rules

diff --git a/.githooks/commit-msg b/.githooks/commit-msg
--- a/.githooks/commit-msg
+++ b/.githooks/commit-msg
@@ -4,11 +4,11 @@
 # - type: fix, ci, feat, chore, docs
 # - scope: optional, alphanumeric and underscores
 # - !: optional, indicates a breaking change
-# - subject: non-empty string
+# - subject: non-empty string with only lowercase letters and no colons and periods
 # - body: optional, can be multiple lines
 
 file="$1"
-regex="^(fix|ci|feat|chore|docs)(?:\(([[\w_]+)\))?(!)?: ([^\n]+)(?:\n\n([^\n][\s\S]+))?\Z"
+regex="^(fix|ci|feat|chore|docs)(?:\(([[\w_]+)\))?(!)?: ([^\nA-Z\.:]+)(?:\n\n([^\n][\s\S]+))?\Z"
 # This regex matches all parts into groups, but there is no way to make grep return
 # only specific groups, so we just check for a full match.
 
@@ -30,7 +30,7 @@ else
 	echo "  Types:   required: fix, ci, feat, chore, docs" >&2
 	echo "  Scope:   optional: alphanumeric and underscores" >&2
 	echo "  !:       optional: indicates a breaking change" >&2
-	echo "  Subject: required: non-empty string" >&2
+	echo "  Subject: required: non-empty string with only lowercase letters and no colons or periods" >&2
 	echo "  Body:    optional: anything" >&2
 	echo "------------------------------------------------" >&2
 	exit 1
